version: '3'

services:
  postgres:
    image: "postgres:14"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=rumor
    ports:
      - "9001:5432"
    networks:
      - rumor
    volumes:
      - pgdata:/var/lib/postgresql/data


  user_service:
    build: ./user-service
    ports:
      - "50057:50057"
      - "3007:3007"
    networks:
      - rumor
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3007" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    restart: always

  invite_request_service:
    build: ./invite-request-service
    ports:
      - "50060:50060"
      - "3008:3008"
    networks:
      - rumor
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3008" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    restart: always

  guest_service:
    build: ./guest-service
    ports:
      - "50059:50059"
      - "3009:3009"
    networks:
      - rumor
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3009" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    restart: always

  event_service:
    build: ./event-service
    ports:
      - "50058:50058"
      - "3010:3010"
    networks:
      - rumor
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3010" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    restart: always

  api_gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - rumor
    depends_on:
      user_service:
        condition: service_started
      guest_service:
        condition: service_started
      invite_request_service:
        condition: service_started
      event_service:
        condition: service_started

    restart: always

volumes:
  pgdata:
    name: postgres-data
    driver: local
networks:
  rumor:
    driver: bridge
